### ISSUE TITLE
omcproxy / LEDE Reboot (17.01.0, r3205-59508e3): does not start on boot

### ISSUE THREAD

**Issue by tvogel** [openwrt/omcproxy#3]
I have set up omcproxy to run on a DHCP interface named "entertain" for Telekom EntertainTV (VLAN 8). I can start omcproxy manually and it works fine. However, after reboot, the process is not running and I don't find any hints in the logs, even after enabling OPTIONS="-v".

Could it be, the procd triggers don't work?

**Comment by tvogel** [comment]
My workaround:
```
root@gw:~# cat /etc/hotplug.d/iface/99-omcproxy 
#!/bin/sh
case "$ACTION" in
ifup|ifdown)
/etc/init.d/omcproxy restart
;;
esac
```

**Comment by howl** [comment]
I have checked the triggers and they are ok. The problem is because the script it self checks it's own variable $PROXIES is empty and then exits 0. one simple solution is to comment out line number 117 "	[ -n "$PROXIES" ] || return 0" I think that there are no adverse effects by doing it because the triggers makes it start when it should.

**Comment by howl** [comment]
This issue is solved with https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=df8f8bad082ea5280c19c9091c099b28b7e2fc67 and https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=d405edb481bb08ee5db482142c65064902899bd3

**Comment by tiagogaspar8** [comment]
> I have checked the triggers and they are ok. The problem is because the script it self checks it's own variable $PROXIES is empty and then exits 0. one simple solution is to comment out line number 117 "	[ -n "$PROXIES" ] || return 0" I think that there are no adverse effects by doing it because the triggers makes it start when it should.

Yeah that worked for me, Is that ever going to get fixed in Openwrt?

**Comment by tiagogaspar8** [comment]
It still doesn't work for me if I don't comment out that line, what can be wrong?

**Comment by howl** [comment]
The commit is in the development tree.

**Comment by tiagogaspar8** [comment]
Let me see if I got this straight, if I build a image from the latest trunk it works? 😅😅😅

**Comment by howl** [comment]
You can simply copy over your installation the omcproxy.init file in /etc/init.d/omcproxy

**Comment by tiagogaspar8** [comment]
Yes, but isn't it supposed to work by default? That's why I'm telling you this ahahah

**Comment by howl** [comment]
@tiagogaspar8, yrs it works by default in snapshot and the next stable release, backport it if you want in the actual stable. Or simply copy the init file as stated before.

**Comment by tiagogaspar8** [comment]
You were right, sorry for the confusion, as this is solved can't this issue be closed? 😄

**Comment by howl** [comment]
Sure, but that can only be done by the maintainer.
